twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        myStuff: someParam
        projectDir: '%kernel.project_dir%'

when@test:
    twig:
        strict_variables: true